version: '2.4'

services:

  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123qwe"
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:114.0
    shm_size: '2gb'
    restart: always
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  web:
    container_name: simplePythonFlask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
      - selenium
    command: python3 app.py

  web_initiate_db:
    container_name: simple-python-flask_init_db
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    command: python3 create_db.py

networks:
  default:
    name: app-network