name : Container image build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login Registry
        uses: docker/login-actions@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extrair Metadados
        id: metadado
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}
      - name: Build and Push
        uses: docker/build-push-action@5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.metadado.outputs.tags }}
          labels: ${{ steps.metadado.outputs.labels }}
       
   