name: "CI/CD - Test"

on:
  pull_request:
    branches:
      - "*"

env:
  IMAGE_NAME: ubuntu:latest

jobs:
  test:
    name: "Teste de Aplicação"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        container:
          - "python:3.9-slim"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Apt get
        run: |
          for i in 1 2 3; do
            apt-get update --fix-missing && \
            apt-get install -y --no-install-recommends python3-mysqldb libmariadb-dev gcc && \
            break
            sleep 5
          done

      - name: Install dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          nosetests --with-xunit --with-coverage --cover-package=project test_users.py

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            *.xml